configName: Trinket_USB_2
folderName: USB_2
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: ATSAMD21E18A
projectName: USB_2
settings:
  PackageFilter: audio;bsp;bt;core;csp;csp_apps_sam_d21_da1;Devices;dev_packs;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21a\atdf\ATSAMD21E18A.atdf
